name: push-actions
on: [push]
jobs:
  build-job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: scripts/install
      - run: git config --global user.name github-actions
      - run: git config --global user.email github-actions@github.com
      - run: npm run push-action
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          DKR_USER: ${{ secrets.DKR_USER }}
          DKR_PWD: ${{ secrets.DKR_PWD }}
